name: Release 

# Trigger the workflow on every push
on:
  push:
    branches:
      - '*'  # Trigger on commits to any branch
    paths:
      - '**'  # Trigger on changes to any file in the repository

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Prepare deps
        run: |
          sudo apt update
          sudo apt install libarchive-tools qemu-user-static mtools u-boot-tools xz-utils
          
      - name: Download files
        run: |
          filename=$(basename https://dietpi.com/downloads/images/DietPi_OdroidC4-ARMv8-Bookworm.img.xz)
          wget https://dietpi.com/downloads/images/DietPi_OdroidC4-ARMv8-Bookworm.img.xz -O $filename
          echo "Downloaded file: $filename"
          ls -l 

      - name: Check file format
        run: |
          filetype=$(file -b $filename)
          echo "File type: $filetype"
          # Check if the file is xz-compressed
          if [[ "$filetype" == *"XZ compressed data"* ]]; then
            echo "Extracting XZ file..."
            unxz $filename
            img_file="${filename%.xz}"
          else
            echo "File format not supported or recognized."
            exit 1

      - name: Verify extracted file
        run: |
          echo "Checking if extracted image exists..."
          if [[ ! -f "$img_file" ]]; then
            echo "Error: Extracted image not found!"
            exit 1
          fi

      - name: Build
        run: |
          sudo bash ./build.sh "$img_file"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: Nightly
          tag: nightly
          artifacts: out/latest/*
          allowUpdates: true
          removeArtifacts: true
