name: Release 
on:
  workflow_dispatch: 
   inputs:
      file_urls:
        description: 'Comma-separated file URLs to download, e.g., https://example.com/file1.zip,https://example.com/file2.zip'
        required: true
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Prepare deps
        run: |
          sudo apt update
          sudo apt install libarchive-tools qemu-user-static mtools u-boot-tools xz-utils

      - name: Create download directory
        run: mkdir -p download

      - name: Download files
        run: |
          filename=$(basename ${{github.event.inputs.file_urls}})
          curl -L ${{github.event.inputs.file_urls}} -o download/$filename
          echo "Downloaded file: $filename"
          ls -l download/

      - name: Check file format
        run: |
          filetype=$(file -b download/$filename)
          echo "File type: $filetype"
          # Check if the file is xz-compressed
          if [[ "$filetype" == *"XZ compressed data"* ]]; then
            echo "Extracting XZ file..."
            unxz download/$filename
            img_file="${filename%.xz}"
          else
            echo "File format not supported or recognized."
            exit 1

      - name: Build
        run: |
          cp ./build.sh download
          cd download
          # Pass the .img file to build.sh
          sudo bash ./build.sh "$img_file"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: Nightly
          tag: nightly
          artifacts: out/latest/*
          allowUpdates: true
          removeArtifacts: true
