name: Release 
on:
  workflow_dispatch: 
   inputs:
      file_urls:
        description: 'Comma-separated file URLs to download, e.g., https://example.com/file1.zip,https://example.com/file2.zip'
        required: true
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Prepare deps
        run: |
          sudo apt update
          sudo apt install libarchive-tools qemu-user-static mtools u-boot-tools 
      - name: Create download directory
        run: mkdir -p download
      - name: Download files
        run: |
          filename=$(basename ${{github.event.inputs.file_urls}})
          curl -L ${{github.event.inputs.file_urls}} -o download/$filename
      - name: build
        run: |
          cp ./build download
          sudo ./build.sh
      - name: Pack sources
        run: |
          tar -cf src.tar src
          tar -cf bin.tar bin
      - name: Save sources
        uses: actions/cache/save@v3
        with:
          path: src.tar
          key: ${{ runner.os }}-src-${{ hashFiles('src.tar') }}
      - name: Save binaries
        uses: actions/cache/save@v3
        with:
          path: bin.tar
          key: ${{ runner.os }}-bin-${{ hashFiles('bin.tar') }}
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: Nightly
          tag: nightly
          artifacts: out/latest/*
          allowUpdates: true
          removeArtifacts: true
